### ISSUE TITLE
Incompatible with Valheim+

### ISSUE THREAD

**Issue by Amunsul** [blaxxun-boop/Mining#10]
Your mod doesnt load. when i check BepInEx logs, it says the following for two of your mods. 

[Error  :   BepInEx] Could not load [Mining 1.1.5] because it is incompatible with: org.bepinex.plugins.valheim_plus
[Error  :   BepInEx] Could not load [Ranching 1.1.3] because it is incompatible with: org.bepinex.plugins.valheim_plus

Is there a known workaround? Fix planned? Or Will your mods and Valheim+ just never be compatible. Thanks for looking into this, let me know if you need more info, logs, etc.

**Comment by blaxxun-boop** [comment]
https://github.com/blaxxun-boop/PassivePowers/issues/5
