### ISSUE TITLE
[BUG] Resources in Crypts are appearing outside

### ISSUE THREAD

**Issue by kastleghost** [blaxxun-boop/Mining#9]
Another bugpost has mentioned it.  Seems that Crypts specifically, have issues with resources, using this mod.  Its mostly noticeable in Sunken Crypts due to mining nature.  Even if you turn off the explosion, Iron scraps will show up around Swamp area instead.

**Comment by blaxxun-boop** [comment]
Not a bug, just the way the scrap piles are set up in vanilla.
![image](https://github.com/blaxxun-boop/Mining/assets/80852900/510c93f7-91b3-4b95-af85-6b3a490a4598)
As you can see, the biggest part of the scrap pile is outside of the dungeon. So, if you destroy all of it, the stuff will drop down outside of the dungeon.

No idea, if that can be prevented and if that really is worth the time.
